# Generated by Django 3.1.3 on 2021-07-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('htmlandcss3', 'htmlandcss3'), ('javascript', 'javascript'), ('django', 'django')], max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
