# Generated by Django 3.1.3 on 2021-07-30 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('htmlandcss3', 'htmlandcss3'), ('javascript', 'javascript'), ('django', 'django')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
