# Generated by Django 3.1.3 on 2021-07-30 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categoryone',
        ),
        migrations.AddField(
            model_name='project',
            name='categorythree',
            field=models.CharField(choices=[('htmlandcss3', 'htmlandcss3'), ('javascript', 'javascript'), ('django', 'django')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='categorytwo',
            field=models.CharField(choices=[('htmlandcss3', 'htmlandcss3'), ('javascript', 'javascript'), ('django', 'django')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
