# Generated by Django 3.1.3 on 2021-07-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210730_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categorythree',
            field=models.CharField(blank=True, choices=[('htmlandcss3', 'htmlandcss3'), ('javascript', 'javascript'), ('django', 'django')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='categorytwo',
            field=models.CharField(blank=True, choices=[('htmlandcss3', 'htmlandcss3'), ('javascript', 'javascript'), ('django', 'django')], max_length=200),
        ),
    ]
