# Generated by Django 3.1.3 on 2021-04-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ManyToManyField(to='website.category'),
        ),
    ]
