# Generated by Django 3.1.3 on 2021-04-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='shop',
        ),
    ]
