# Generated by Django 3.1.3 on 2021-04-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
