# Generated by Django 3.1.3 on 2021-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210420_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.FloatField(),
        ),
    ]
