# Generated by Django 3.2.8 on 2021-11-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20211102_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ManyToManyField(to='website.Category'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(to='website.Category'),
        ),
    ]
