# Generated by Django 3.2.8 on 2021-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20211102_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ManyToManyField(to='website.Category'),
        ),
        migrations.DeleteModel(
            name='shop',
        ),
    ]
